<?php

/**
 * Manage log generated by moveup-wp
 *
 * @since      0.0.1
 *
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( 'MoveUpWPLogger' ) ) {

	class MoveUpWPLogger {

		/**
		 * Store log
		 *
		 * @param $content
		 * @param $source
		 * @param $level
		 *
		 * @return void
		 */
		public static function wc_log( $content, $source = 'debug', $level = 'info' ) {
			$content = strip_tags( $content );
			$log     = wc_get_logger();
			$log->log( $level, $content, [
				'source' => 'moveup-wp-' . $source
			] );
			error_log( $content );
		}
	}
}
